# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{shuriken}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Darcy Laycock"]
  s.date = %q{2010-06-11}
  s.description = %q{Simple Namespace support for JS + Other niceties, packaged as a Barista framework}
  s.email = %q{sutto@sutto.net}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "README.md",
     "Rakefile",
     "coffeescripts/shuriken.coffee",
     "coffeescripts/shuriken/mixins.coffee",
     "coffeescripts/shuriken/mixins/callbacks.coffee",
     "javascripts/shuriken.js",
     "javascripts/shuriken/mixins.js",
     "javascripts/shuriken/mixins/callbacks.js",
     "javascripts/shuriken/test.js",
     "javascripts/shuriken/test/assertions.js",
     "javascripts/shuriken/test/reporters.js",
     "lib/shuriken.rb",
     "shuriken.gemspec",
     "tests.watchr",
     "tests/basic_namespace_tests.coffee",
     "tests/template.erb",
     "vendor/jasmine-0.10.0/MIT.LICENSE",
     "vendor/jasmine-0.10.0/README.markdown",
     "vendor/jasmine-0.10.0/doc/files.html",
     "vendor/jasmine-0.10.0/doc/index.html",
     "vendor/jasmine-0.10.0/doc/symbols/_global_.html",
     "vendor/jasmine-0.10.0/doc/symbols/jasmine.Block.html",
     "vendor/jasmine-0.10.0/doc/symbols/jasmine.Clock.html",
     "vendor/jasmine-0.10.0/doc/symbols/jasmine.Env.html",
     "vendor/jasmine-0.10.0/doc/symbols/jasmine.JsApiReporter.html",
     "vendor/jasmine-0.10.0/doc/symbols/jasmine.Matchers.html",
     "vendor/jasmine-0.10.0/doc/symbols/jasmine.MultiReporter.html",
     "vendor/jasmine-0.10.0/doc/symbols/jasmine.NestedResults.html",
     "vendor/jasmine-0.10.0/doc/symbols/jasmine.Reporter.html",
     "vendor/jasmine-0.10.0/doc/symbols/jasmine.Runner.html",
     "vendor/jasmine-0.10.0/doc/symbols/jasmine.Spec.html",
     "vendor/jasmine-0.10.0/doc/symbols/jasmine.Spy.html",
     "vendor/jasmine-0.10.0/doc/symbols/jasmine.Suite.html",
     "vendor/jasmine-0.10.0/doc/symbols/jasmine.html",
     "vendor/jasmine-0.10.0/doc/symbols/jasmine.util.html",
     "vendor/jasmine-0.10.0/doc/symbols/src/lib_TrivialReporter.js.html",
     "vendor/jasmine-0.10.0/doc/symbols/src/src_Block.js.html",
     "vendor/jasmine-0.10.0/doc/symbols/src/src_Env.js.html",
     "vendor/jasmine-0.10.0/doc/symbols/src/src_JsApiReporter.js.html",
     "vendor/jasmine-0.10.0/doc/symbols/src/src_Matchers.js.html",
     "vendor/jasmine-0.10.0/doc/symbols/src/src_MultiReporter.js.html",
     "vendor/jasmine-0.10.0/doc/symbols/src/src_NestedResults.js.html",
     "vendor/jasmine-0.10.0/doc/symbols/src/src_PrettyPrinter.js.html",
     "vendor/jasmine-0.10.0/doc/symbols/src/src_Queue.js.html",
     "vendor/jasmine-0.10.0/doc/symbols/src/src_Reporter.js.html",
     "vendor/jasmine-0.10.0/doc/symbols/src/src_Reporters.js.html",
     "vendor/jasmine-0.10.0/doc/symbols/src/src_Runner.js.html",
     "vendor/jasmine-0.10.0/doc/symbols/src/src_Spec.js.html",
     "vendor/jasmine-0.10.0/doc/symbols/src/src_Suite.js.html",
     "vendor/jasmine-0.10.0/doc/symbols/src/src_WaitsBlock.js.html",
     "vendor/jasmine-0.10.0/doc/symbols/src/src_WaitsForBlock.js.html",
     "vendor/jasmine-0.10.0/doc/symbols/src/src_base.js.html",
     "vendor/jasmine-0.10.0/doc/symbols/src/src_mock-timeout.js.html",
     "vendor/jasmine-0.10.0/doc/symbols/src/src_util.js.html",
     "vendor/jasmine-0.10.0/example/example_runner.html",
     "vendor/jasmine-0.10.0/example/spec/example_suite.js",
     "vendor/jasmine-0.10.0/lib/TrivialReporter.js",
     "vendor/jasmine-0.10.0/lib/consolex.js",
     "vendor/jasmine-0.10.0/lib/jasmine-0.10.0.js",
     "vendor/jasmine-0.10.0/lib/jasmine.css",
     "vendor/jasmine-0.10.0/spec/runner.html",
     "vendor/jasmine-0.10.0/spec/suites/CustomMatchersSpec.js",
     "vendor/jasmine-0.10.0/spec/suites/EnvSpec.js",
     "vendor/jasmine-0.10.0/spec/suites/ExceptionsSpec.js",
     "vendor/jasmine-0.10.0/spec/suites/JsApiReporterSpec.js",
     "vendor/jasmine-0.10.0/spec/suites/MatchersSpec.js",
     "vendor/jasmine-0.10.0/spec/suites/MockClockSpec.js",
     "vendor/jasmine-0.10.0/spec/suites/MultiReporterSpec.js",
     "vendor/jasmine-0.10.0/spec/suites/NestedResultsSpec.js",
     "vendor/jasmine-0.10.0/spec/suites/PrettyPrintSpec.js",
     "vendor/jasmine-0.10.0/spec/suites/QueueSpec.js",
     "vendor/jasmine-0.10.0/spec/suites/ReporterSpec.js",
     "vendor/jasmine-0.10.0/spec/suites/RunnerSpec.js",
     "vendor/jasmine-0.10.0/spec/suites/SpecRunningSpec.js",
     "vendor/jasmine-0.10.0/spec/suites/SpecSpec.js",
     "vendor/jasmine-0.10.0/spec/suites/SpySpec.js",
     "vendor/jasmine-0.10.0/spec/suites/SuiteSpec.js",
     "vendor/jasmine-0.10.0/spec/suites/TrivialReporterSpec.js",
     "vendor/jasmine-0.10.0/spec/suites/UtilSpec.js",
     "vendor/jquery.js",
     "wip-coffeescripts/example_test.coffee",
     "wip-coffeescripts/test.coffee",
     "wip-coffeescripts/test/assertions.coffee",
     "wip-coffeescripts/test/reporters.coffee"
  ]
  s.homepage = %q{http://github.com/Sutto/shuriken}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple Namespace support for JS + Other niceties, packaged as a Barista framework}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

