# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{shuriken}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Darcy Laycock"]
  s.date = %q{2010-05-03}
  s.description = %q{Simple Namespace support for JS + Other niceties, packaged as a Barista framework}
  s.email = %q{sutto@sutto.net}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "coffeescripts/shuriken.coffee",
     "coffeescripts/shuriken/mixins.coffee",
     "coffeescripts/shuriken/mixins/callbacks.coffee",
     "lib/shuriken.rb",
     "shuriken.gemspec",
     "wip-coffeescripts/test.coffee"
  ]
  s.homepage = %q{http://github.com/Sutto/shuriken}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Simple Namespace support for JS + Other niceties, packaged as a Barista framework}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

